### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by spkesDE** [spkesDE/com.spkes.telegramNotifications#8]
High Prio

- [x] Update Settings Page to homey.css
   - [x] Resolve css conflicts
- [x] BLL Support
   - [x] Needs Testing
   - [x] Waiting for update from BLL
   - [x] Waiting for Web-Api fix
- [x] #9 
- [x] #12
- [x] Custom/Replace Text for Question so you can add tokens to the string.
- [x] Editable Colums
- [x] Add Timestamp token to WHEN card
- [x] #14 
- [x] #16 
- [x] Delete by customId
- [x] #18

Low Prio

- [x] #10
- [x] #15
- [ ] Create Question via Flow card with default answers
- [ ] Create Question via Flow card with String input and ; as a separator
